### ISSUE TITLE
press cmd + hover on version number show warning

### ISSUE THREAD

**Issue by tjx666** [zyrong/vscode-node-modules#1]
![image](https://user-images.githubusercontent.com/41773861/155081733-de90fda2-a865-4de6-8de2-f1426bc0c39f.png)

package.json:

```json
{
    "name": "packagejsonissue",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "dependencies": {
        "axios": "0.0.1"
    }
}
```

If the version number is prefix with `^` will no issue, like `"axios": "^0.0.1"`

Versions: 

VSCode: 1.65.0-insider
MacOS: 12.2.2
node_modules: v1.1.1

**Comment by zyrong** [comment]
package.json whether there is a node_modules in the directory where the path is located

**Comment by tjx666** [comment]
@zyrong

![image](https://user-images.githubusercontent.com/41773861/155124087-138c8604-c097-43c1-b352-8985e0483486.png)

**Comment by zyrong** [comment]
Thank you. The problem has been fixed.
