### ISSUE TITLE
support exclude module name when hover tooltip

### ISSUE THREAD

**Issue by tjx666** [zyrong/vscode-node-modules#17]
So I can exclude the local modules when using webpack alias:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/41773861/190453576-4995fa1f-a7a3-4777-a21b-62166c02d77c.png">

**Comment by zyrong** [comment]
> So I can exclude the local modules when using webpack alias:
> 
> <img alt="image" width="969" src="https://user-images.githubusercontent.com/41773861/190453576-4995fa1f-a7a3-4777-a21b-62166c02d77c.png">

'@/store' 匹配为 'store' 是一个bug
