### ISSUE TITLE
包名悬浮提示的几个建议

### ISSUE THREAD

**Issue by tjx666** [zyrong/vscode-node-modules#4]
1. 目前实现依赖解析 ast，感觉有点杀鸡用牛刀，如果可以的话全用正则实现会性能会更好
2. 目前代码中存在拼接正则的情况: https://github.com/zyrong/vscode-node-modules/blob/master/src/pkgname-hover-tip.ts#L60
    - 可以的话不要用拼接正则，有些情况拼接出来的正则性能很差
    - 拼接出来的正则非法情况没有 try/catch 处理
3. https://github.com/zyrong/vscode-node-modules/blob/master/src/pkgname-hover-tip.ts#L60 range 有可能返回的是 undefined, 这会导致 hoverWord 是整个文件的文本，从而导致拼出非法的正则

代码没细看，可能有说错的地方。

**Comment by tjx666** [comment]
我之前也实现的提取包名的代码：https://github.com/tjx666/view-github-repository/blob/master/src/util.ts#L54

**Comment by zyrong** [comment]
好的我完善下判断，正则匹配只会匹配一行性能可以忽略不计，ast能更准确的匹配，正则我感觉有些边界情况想不到，例如: 
```
import a from 'xxx'
"import a from 'xxx'" // 一个包含import的字符串
```
，一般导入语句都在顶部，我做了优化，所以通常情况性能还是可以的。

**Comment by tjx666** [comment]
感觉包含 import 的字符串给提示没啥关系，直接当它是个 feature

**Comment by tjx666** [comment]
https://github.com/zyrong/vscode-node-modules/pull/5/commits/0d8f07c14eadf94cd416f84561d4e3e34c7192cd

**Comment by tjx666** [comment]
> 看最近一次提交：[0d8f07c](https://github.com/zyrong/vscode-node-modules/commit/0d8f07c14eadf94cd416f84561d4e3e34c7192cd)

你没处理到左边单引号右边双引号的情况

**Comment by zyrong** [comment]
> > 看最近一次提交：[0d8f07c](https://github.com/zyrong/vscode-node-modules/commit/0d8f07c14eadf94cd416f84561d4e3e34c7192cd)
> 
> 你没处理到左边单引号右边双引号的情况

ast parse会失败，然后直接return
