### ISSUE TITLE
package.json 包名点击跳转好像没用了

### ISSUE THREAD

**Issue by tjx666** [zyrong/vscode-node-modules#6]
Version:

- MacOS: 12.4
- VSCode: 1.69.0-insider

**Comment by tjx666** [comment]
@zyrong

**Comment by zyrong** [comment]
> 我觉得永远不应该拿用户的输入去拼接正则：
> 
> ![image](https://user-images.githubusercontent.com/41773861/173547074-62edb17b-cabb-4ad5-8fc9-627762c82190.png)

好的，包名跳转失效，是因为这个原因导致的么？

**Comment by zyrong** [comment]
> 我觉得永远不应该拿用户的输入去拼接正则：
> 
> ![image](https://user-images.githubusercontent.com/41773861/173547074-62edb17b-cabb-4ad5-8fc9-627762c82190.png)

已删除原来的正则判断，检测逻辑重构了，具体看这个commit，https://github.com/zyrong/vscode-node-modules/commit/4c5023b981a7c4690529f9bcf133c83dfbeb63ff

**Comment by tjx666** [comment]
现在的代码跑不起来呀：

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/177050177-247b8901-0f28-476a-b33e-99dec65ab7bf.png">

集成测试的话可以参考：https://github.com/tjx666/vscode-extension-boilerplate

**Comment by zyrong** [comment]
> 现在的代码跑不起来呀：
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/41773861/177050177-247b8901-0f28-476a-b33e-99dec65ab7bf.png">
> 
> 集成测试的话可以参考：https://github.com/tjx666/vscode-extension-boilerplate

测试已经写了一部分了，没推，最近比较忙，要晚点才能写完，测试目录的ts问题全部注释掉应该就能启动
