### ISSUE TITLE
支持package-lock.json

### ISSUE THREAD

**Issue by eightHundreds** [zyrong/vscode-node-modules#7]
有些包是没列在package.json的

**Comment by zyrong** [comment]
后续可以支持，目前可以使用search package或search node_modules的功能先用下

**Comment by zyrong** [comment]
> 有些包是没列在package.json的

后续可以支持，目前可以使用search package或search node_modules的功能先用下

**Comment by zyrong** [comment]
> 有些包是没列在package.json的

v1.5.0，已支持该功能

**Comment by zyrong** [comment]
> > 有些包是没列在package.json的
> 
> v1.5.0，已支持该功能

更新下插件就可以用了
