### ISSUE TITLE
hover tip 再加一行显示包大小

### ISSUE THREAD

**Issue by tjx666** [zyrong/vscode-node-modules#8]
相关链接：
- https://github.com/pastelsky/bundlephobia
- https://github.com/thelostone-mc/importcost/blob/master/lib/size.js#L17

**Comment by zyrong** [comment]
> 相关链接：
> 
> * https://github.com/pastelsky/bundlephobia
> * https://github.com/thelostone-mc/importcost/blob/master/lib/size.js#L17

👌

**Comment by zyrong** [comment]
v1.5.0，已支持该功能
